export enum AssessmentDeliveryEnum {
  LIVE_PROCTORING = 'LIVE_PROCTORING',
  AUTO_PROCTORING = 'AUTO_PROCTORING',
  ONLINE_NO_PROCTORING = 'ONLINE_NO_PROCTORING',
  ON_PREMISE_SECURE_BROWSER = 'ON_PREMISE_SECURE_BROWSER',
  ON_PREMISE_NO_SECURE_BROWSER = 'ON_PREMISE_NO_SECURE_BROWSER',
  E_PAPER = 'E_PAPER',
  BYOD = 'BYOD'
}

export enum ProctoredCategoryEnum {
  LIVE_PROCTORING = 'LIVE_PROCTORING',
  AUTO_PROCTORING = 'AUTO_PROCTORING',
}

export enum UnsupervisedCategoryEnum {
  ONLINE_SECURE_BROWSER = 'ONLINE_SECURE_BROWSER',
  ONLINE_NO_SECURE_BROWSER = 'ONLINE_NO_SECURE_BROWSER'
}


export enum CentreBasedCategoryEnum {
  OFFLINE_SECURE_BROWSER = 'OFFLINE_SECURE_BROWSER',
  OFFLINE_NO_SECURE_BROWSER = 'OFFLINE_NO_SECURE_BROWSER',
  BYOD = 'BYOD'
}

export enum E_PaperEnum {
  E_PAPER = 'E_PAPER'
}