export enum AssessmentDeliveryEnum {
  LIVE_PROCTORING = 'LIVE_PROCTORING',
  AUTO_PROCTORING = 'AUTO_PROCTORING',
  ONLINE_NO_PROCTORING = 'ONLINE_NO_PROCTORING',
  ON_PREMISE_SECURE_BROWSER = 'ON_PREMISE_SECURE_BROWSER',
  ON_PREMISE_NO_SECURE_BROWSER = 'ON_PREMISE_NO_SECURE_BROWSER',
}
