export enum BlockQuestionsSelectionTypesEnum {
  /* AUTOMATED_WITH_CRITERIA = 'AUTOMATED_WITH_CRITERIA',
  AUTOMATED_WITHOUT_CRITERIA = 'AUTOMATED_WITHOUT_CRITERIA', */
  AUTOMATED = 'AUTOMATED',
  MANUAL = 'MANUAL',
}
