export enum Role {
  ANALYTIC = "ANALYTIC",
  ADMIN = 'ADMIN',
  AUTHOR = 'AUTHOR',
  CENTER_ADMIN = 'CENTER_ADMIN',
  EXAMINER = 'EXAMINER',
  MARKER = 'MARKER',
  MODERATOR = 'MODERATOR',
  MONITOR = 'MONITOR',
  PROCTOR_ADMIN = "PROCTOR_ADMIN",
}
