/**
 * Group List
 */

const CenterData = [
  {
    id: 701,
    backgroundImg: "assets/images/small/img-9.jpg",
    userImage: "assets/images/users/avatar-2.jpg",
    name: "Nancy Martino",
    location: "Lagos",
    capacity: 225,
    taskCount: 197,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 702,
    backgroundImg: "assets/images/small/img-12.jpg",
    userImage: null,
    userShortName: "HB",
    name: "Henry Baird",
    location: "Akure",
    capacity: 352,
    taskCount: 376,
    centerType: "custom center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 703,
    backgroundImg: "assets/images/small/img-11.jpg",
    userImage: "assets/images/users/avatar-3.jpg",
    name: "Frank Hook",
    location: "Dubai",
    capacity: 162,
    taskCount: 192,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 704,
    backgroundImg: "assets/images/small/img-1.jpg",
    userImage: "assets/images/users/avatar-8.jpg",
    name: "Jennifer Carter",
    location: "Canada",
    capacity: 241,
    taskCount: 205,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 705,
    backgroundImg: "assets/images/small/img-1.jpg",
    userImage: null,
    userShortName: "ME",
    name: "Megan Elmore",
    location: "Ukraine",
    capacity: 201,
    taskCount: 263,
    centerType: "custom center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 706,
    backgroundImg: "assets/images/small/img-2.jpg",
    userImage: "assets/images/users/avatar-4.jpg",
    name: "Alexis Clarke",
    location: "Yolo",
    capacity: 132,
    taskCount: 147,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 707,
    backgroundImg: "assets/images/small/img-4.jpg",
    userImage: "",
    userShortName: "NC",
    name: "Nathan Cole",
    location: "Bauchi",
    capacity: 352,
    taskCount: 376,
    centerType: "custom center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 708,
    backgroundImg: "assets/images/small/img-7.jpg",
    userImage: "assets/images/users/avatar-6.jpg",
    name: "Joseph Parker",
    location: "Taraba",
    capacity: 64,
    taskCount: 93,
    centerType: "custom center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 709,
    backgroundImg: "assets/images/small/img-3.jpg",
    userImage: "assets/images/users/avatar-5.jpg",
    name: "Erica Kernan",
    location: "Akwa-Ibom",
    capacity: 345,
    taskCount: 298,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 710,
    backgroundImg: "assets/images/users/avatar-5.jpg",
    userImage: null,
    userShortName: "DP",
    name: "Donald Palmer",
    location: "Kogi",
    capacity: 95,
    taskCount: 135,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 711,
    backgroundImg: "assets/images/small/img-8.jpg",
    userImage: "assets/images/users/avatar-7.jpg",
    name: "Jack Gough",
    location: "Enugu",
    capacity: 87,
    taskCount: 121,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
  {
    id: 712,
    backgroundImg: "assets/images/small/img-6.jpg",
    userImage: null,
    userShortName: "MW",
    name: "Marie Ward",
    location: "Gombe",
    capacity: 145,
    taskCount: 210,
    centerType: "betaExam center",
    systemTypes: "thin client",
          parameters: [{field:'level', value:'200'}, {field: 'department', value:'accounting'}],

    networkSpeed: "200mbps",
  },
];

export { CenterData };
